site_name: The World
nav:
  - Home: index.md
  - Locations: 
    - locations/index.md
    - The city of Khendarohm:
      - locations/khendarohm/index.md
extra_css:
  - css/style.css
extra_js:
  - js/index.js
site_author: Ferre "Ferwardo" Snyers
theme:
  name: material
  prev_next_buttons_location: none
  features:
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
plugins:
  - search
draf_docs: |
  drafts/
  _unpublished.md
